export { fs } from '@magic/fs'

export { addTrailingSlash } from './addTrailingSlash.mjs'
export { applyWebRoot } from './applyWebRoot.mjs'
export { getBabelConf } from './babel/index.mjs'
export { CHECK_PROPS } from './CHECK_PROPS.mjs'
// export { compress } from './compress.mjs'
export { createFileHash } from './createFileHash.mjs'
export { findModuleStyles } from './findModuleStyles.mjs'
export { getGitConfig } from './getGitConfig.mjs'
export { getPages } from './getPages.mjs'
export { handleDependencies } from './handleDependencies.mjs'
export { handleStyleFunctions } from './handleStyleFunctions.mjs'
export { isLocalPath } from './isLocalPath.mjs'
export { isUpperCase } from './isUpperCase.mjs'
// export { minifyImages } from './minifyImages.mjs'
export { stringifyObject } from './stringifyObject.mjs'
export { toCamel } from './toCamel.mjs'
export { toPascal } from './toPascal.mjs'
export { writeFile } from './writeFile.mjs'
export { writeServer } from './writeServer.mjs'
export { xc } from './xc.mjs'
